### ISSUE TITLE
Page builder issue

### ISSUE THREAD

**Issue by 4j4yk** [mageprince/magento2-FAQ#39]
### Preconditions
     2.3.3 with page builder enabled

#### Steps to reproduce (*)
1. Install latest version of this module
2. go to admin and trying editing html block for any faq 

![Screen Shot 2020-08-06 at 6 27 36 PM](https://user-images.githubusercontent.com/21245817/89588851-81fbdf80-d812-11ea-9dcb-b0d0544fded8.png)

### Expected result
      Open html editor popup 

### Actual result 
     After clicking on the icon nothing happens.

**Comment by the-lensky** [comment]
Same problem this button do nothing, cant edit like html.

**Comment by YYDCZ** [comment]
I encountered the same problem in 2.4.3

**Comment by mageprince** [comment]
Hi, @4j4yk @the-lensky @YYDCZ This is fixed.
Related Commit: https://github.com/mageprince/magento2-FAQ/commit/c36b1193181d2accbd0fb3b7e73e7e91f89d2fbc

**Comment by carlo-manuel-molina** [comment]
Hi @mageprince ,

This issue still persists on my end.

Mageprince FAQ v 2.0.11
Magento v 2.4.2

I recently updated from 2.0.8 to 2.0.11.

This used to work for FAQ v 2.0.8 and Magento 2.3.*.

Any ideas?
